BEGIN;

DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS appointments;
DROP TYPE appointment_status;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS counties;
DROP TABLE IF EXISTS countries;

COMMIT;
